# Generated by Django 6.0.7 on 2026-07-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='refund_eligible',
            field=models.BooleanField(default=False),
        ),
    ]
