# Generated by Django 6.0.7 on 2026-08-05 07:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0003_event_is_featured_event_is_suppressed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRetryQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('REGISTRATION_CONFIRMED', 'Registration confirmed'), ('WAITLIST_JOINED', 'Waitlist joined'), ('WAITLIST_PROMOTED', 'Waitlist promoted'), ('EVENT_CANCELLED', 'Event cancelled'), ('EVENT_REMINDER', 'Event reminder')], max_length=40)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DEAD', 'Dead')], default='PENDING', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=5)),
                ('last_error', models.TextField(blank=True)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_retries', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_retries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_attempt_at'],
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='notificatio_status_c28feb_idx')],
            },
        ),
    ]
