# Generated by Django 6.0.7 on 2026-07-25 06:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_is_featured_event_is_suppressed'),
        ('registrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('member_count', models.PositiveIntegerField()),
                ('group_token', models.CharField(editable=False, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('WAITLISTED', 'Waitlisted'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_registrations', to='events.event')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_team_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='registration',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='registrations.teamregistration'),
        ),
    ]
