# Generated by Django 6.0.7 on 2026-08-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_teamregistration_registration_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamregistration',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
