# Generated by Django 6.0.7 on 2026-08-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_teamregistration_reminder_sent_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamregistration',
            name='reminder_sent_at',
        ),
        migrations.AddField(
            model_name='registration',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
